services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mysql'
      - 'MYSQL_PASSWORD=mysql'
      - 'MYSQL_ROOT_PASSWORD=mysql'
      - 'MYSQL_USER=mysql'
    ports:
      - '3306:3306'
    networks:
      - database_network

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - database_network

networks:
  database_network:
    name: custom_database_network

#  app:
#    image: resource-aggregator-service
#    build:
#      context: .
#    ports:
#      - '8080:8080'
#    environment:
#      - 'SPRING_DATASOURCE_POSTGRES_URL=jdbc:postgresql://postgres:5432/postgres'
#      - 'SPRING_DATASOURCE_MYSQL_URL=jdbc:mysql://mysql:3306/mysql'
#    depends_on:
#      - mysql
#      - postgres
